kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-europe-north1-c
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
  zone: europe-north1-c
